name: the_palm_project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  video_player: ^1.0.1
  flutter_svg: ^0.19.2+1
  google_fonts: ^1.1.2
  carousel_slider: ^3.0.0
  gooey_carousel: ^0.1.2
  flutter_screenutil: ^4.0.3+1
  auto_animated: ^2.1.0
  flip_card: ^0.4.4
  intl: ^0.16.1
  provider: ^5.0.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  fluttertoast: ^8.0.6
  google_sign_in:
  shared_preferences: ^2.0.6
  http:
  cloud_firestore:
  
      


    


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/video/
    - assets/extras/
    - assets/images/
    - assets/gallery/
    - assets/Logo.svg
    
    

  fonts:
    - family: FjallaOne
      fonts:
        - asset: fonts/FjallaOne-Regular.ttf

    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
        
    - family:  Social_Media_Icons
      fonts:
       - asset: fonts/Social_Media_Icons.ttf