/// Flutter icons Social_Media_Icons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Social_Media_Icons
///      fonts:
///       - asset: fonts/Social_Media_Icons.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Social_Media_Icons {
  Social_Media_Icons._();

  static const _kFontFam = 'Social_Media_Icons';
  static const String _kFontPkg = null;

  static const IconData instagram =
      IconData(0xf16d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_official =
      IconData(0xf230, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
